# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20180228_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_ideas', to='firstapp.User'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='firstapp.User'),
        ),
    ]
