# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20180228_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='total_ideas',
            field=models.IntegerField(default=1),
        ),
    ]
