# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_ideas_total_ideas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pokes', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='likes',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_received', to='firstapp.User'),
        ),
        migrations.AddField(
            model_name='likes',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_sent', to='firstapp.User'),
        ),
    ]
