# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20180228_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='total_pokes',
            new_name='total_likes',
        ),
    ]
