# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20180228_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='total_ideas',
        ),
    ]
