# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_remove_ideas_total_ideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='firstapp.User'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to='firstapp.User'),
        ),
    ]
