# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20180228_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likess_received', to='firstapp.Ideas'),
        ),
    ]
