# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20180228_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='sender',
        ),
        migrations.AddField(
            model_name='ideas',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='firstapp.User'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
