# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20180228_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='likes',
            field=models.ManyToManyField(related_name='_ideas_likes_+', to='firstapp.Ideas'),
        ),
    ]
