# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20180228_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='likes',
        ),
        migrations.AddField(
            model_name='ideas',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='firstapp.User'),
        ),
    ]
