# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20180228_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_likes', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='firstapp.Ideas'),
        ),
        migrations.AddField(
            model_name='like',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to='firstapp.User'),
        ),
    ]
